"""
Generate one benchmark Jupyter notebook per model in the repo.
Each generated notebook contains:
- brief description cell
- env detection (Kaggle vs local + device)
- dataset discovery (uses workspace CSVs)
- lightweight preprocessing example
- a runnable cell that calls the repo benchmark harness or shows a model-specific stub

Run: python notebooks/generate_model_notebooks.py
"""
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os
import re

MODELS = [
    # Phase 1
    "ARIMA",
    "SARIMA",
    "VAR",
    # Phase 2
    "SVR",
    "RandomForest",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    # Phase 3
    "RNN",
    "LSTM",
    "GRU",
    "BiLSTM",
    # Phase 4
    "CNN-LSTM",
    "CNN-GRU",
    "BiLSTM_Attention",
    "Informer",
    "Autoformer",
    "TFT",
    # Phase 5
    "GCN",
    "ST-GCN",
]

OUT_DIR = os.path.join(os.path.dirname(__file__), "generated")
os.makedirs(OUT_DIR, exist_ok=True)

COMMON_IMPORTS = """# Standard imports
import os
import sys
import json
import subprocess
import numpy as np
import pandas as pd
from pathlib import Path

# Device detection (GPU if available)
try:
    import torch
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
except Exception:
    DEVICE = 'cpu'

print('Detected device:', DEVICE)
"""

DATA_DISCOVERY = """# Data discovery
# Adjust these paths if your cleaned CSVs are elsewhere. This repo contains several CSV/NPY files at the project root.
root = Path('..').resolve()
# Prefer cleaned files if present
candidates = [
    root / 'feeds_cleaned_15T.csv',
    root / 'feeds_cleaned.csv',
    root / 'feeds.csv'
]
DATA_PATH = None
for p in candidates:
    if p.exists():
        DATA_PATH = p
        break

if DATA_PATH is None:
    raise FileNotFoundError('No dataset CSV found under repository root. Place cleaned CSV at project root.')

print('Using dataset:', DATA_PATH)

df = pd.read_csv(DATA_PATH)
print('Sample rows:', df.shape)
"""

PREPROCESS_STUB = """# Preprocessing stub
# This cell provides a minimal example. For model-specific preprocessing, replace as needed.
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Example: if target column is 'PM2.5' adjust as necessary
if 'PM2.5' in df.columns:
    target_col = 'PM2.5'
else:
    target_col = df.columns[-1]

# Use a simple tabular slice for quick runs
X = df.drop(columns=[target_col]).fillna(method='ffill').values
y = df[target_col].fillna(method='ffill').values

# Quick train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print('Shapes:', X_train.shape, X_test.shape)
"""

BENCHMARK_CALL_TEMPLATE = """# Run the repo benchmark harness for this model (preferred)
# Edit the command below if your harness location or args differ.
model_name = "{model_name}"
cmd = [
    sys.executable, '-u',
    'data/kaggle_dataset/kaggle_benchmarking_suite.py',
    '--model', model_name,
    '--data_dir', str(DATA_PATH.parent),
    '--output_dir', 'outputs',
    '--city', 'Delhi',
]

print('Running harness:',' '.join(cmd))
subprocess.run(cmd, check=False)
"""

# For purely-statistical models we include a short note about statsmodels usage
STATSNOTE = """> **Note**: ARIMA/SARIMA/VAR typically use `statsmodels`. Use ADF test and differencing before fitting.
"""


def sanitize(name: str) -> str:
    return re.sub(r'[^0-9A-Za-z_-]', '_', name)


for model in MODELS:
    nb = new_notebook()
    title = f"Benchmark — {model}"
    md_intro = new_markdown_cell(f"# {title}\n\nNotebook generated by `generate_model_notebooks.py`.\n\nModel: **{model}**.\n\nThis template auto-detects device (GPU if available), finds a dataset CSV at the repo root, and provides a minimal preprocessing and harness invocation cell.\n")
    nb.cells.append(md_intro)

    nb.cells.append(new_code_cell(COMMON_IMPORTS))
    nb.cells.append(new_code_cell(DATA_DISCOVERY))
    nb.cells.append(new_code_cell(PREPROCESS_STUB))

    # Add model-specific guidance
    if model in ("ARIMA", "SARIMA", "VAR"):
        nb.cells.append(new_markdown_cell(STATSNOTE))
        nb.cells.append(new_code_cell(BENCHMARK_CALL_TEMPLATE.format(model_name=model)))
    elif model in ("Informer", "Autoformer", "TFT"):
        nb.cells.append(new_markdown_cell("**Transformer-class model**: These are computationally heavy. For Kaggle prefer smaller epochs and shorter windows."))
        nb.cells.append(new_code_cell(BENCHMARK_CALL_TEMPLATE.format(model_name=model)))
    else:
        nb.cells.append(new_code_cell(BENCHMARK_CALL_TEMPLATE.format(model_name=model)))

    fname = os.path.join(OUT_DIR, f"benchmark_{sanitize(model)}.ipynb")
    with open(fname, 'w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    print('Wrote', fname)

print('Generated', len(MODELS), 'notebooks in', OUT_DIR)
